webpack_encore:
    output_path: false
    builds:
        admin: '%kernel.project_dir%/public/build/admin'
        front: '%kernel.project_dir%/public/build/front'

framework:
    assets:
        packages:
            admin:
                json_manifest_path: '%kernel.project_dir%/public/build/admin/manifest.json'
            front:
                json_manifest_path: '%kernel.project_dir%/public/build/front/manifest.json'
