import { C } from "vue/helper/V02Component.jsx";

import { getConfig } from "modules/ankoay/index/index_config.js";
import styles from "./Index.scss?module";
import classNames from "classnames";

export default C.make({
    $render(){
        
        return (
            <div>
				Auto-generated by PW Generator
            </div>
        );

    },
});
